### ISSUE TITLE
TCP Brutal

### ISSUE THREAD

**Issue by imagecreation1** [xchacha20-poly1305/husi#38]
Hello.
Could you please add an option to set TCP Brutal up inside the app without making custom JSON config? https://sing-box.sagernet.org/configuration/shared/tcp-brutal/ - here it is, added to the sing-box core.

**Comment by xchacha20-poly1305** [comment]
[v0.6.0-alpha.0](https://github.com/xchacha20-poly1305/husi/releases/tag/v0.6.0-alpha.0)
