### ISSUE TITLE
"VPN required" warning when using proxy-only mode

### ISSUE THREAD

**Issue by Terrance** [xchacha20-poly1305/husi#39]
### Version

```text
Version
0.4.1

Version (sing-box)
sing-box: v1.8.4-dun-0.2.1
go1.21.6@android/arm64
with_conntrack,with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api,with_ech
```

### Description

Using "Proxy only" service mode (behind [Rethink](https://github.com/celzero/rethink-app)), pressing the Connect button shows the following warning toast:

> Routing rule _(rule name)_ relies on the VPN to be in effect, so it is ignored.

The rule in question matches on a destination IP and routes it through an SSH profile, with a second bypass rule to ignore the remaining traffic.

As far as I can tell, this is a false-positive warning -- the routes appear to be working as intended.  I've just migrated here from NekoBox, where I had the same working setup, but no such warning was shown there.

I was also dismissing the VpnService warning at startup, which again isn't applicable to proxy-only mode, though I realise this is more of a consent screen and doesn't change the functionality when Yes is selected.

### Reproduction

1. Settings > Service Mode > Proxy only
2. Configuration > Add Profile (using an SSH profile here; anything will probably do)
3. Route > Create Route (one routing a single IP to the profile, another bypassing `0.0.0.0/0` and `::/0`)
4. Connect

### Logs

```shell
(empty)
```

### Integrity requirements

- [X] I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by xchacha20-poly1305** [comment]
Use [v0.6.0-beta.0](https://github.com/xchacha20-poly1305/husi/releases/tag/v0.6.0-beta.0), and reset your route rules.

**Comment by Terrance** [comment]
I've just updated to 0.6.0 but this doesn't seem to be working at all for me now:

* recreating a rule is valid (the rule itself just defines `domain` and `outbound`), but then trying to edit one I get:
  > **Empty Route**
  > Set some rules before saving

* after fiddling with filling/blanking other fields it accepted an edit but showed "1 Application" in the list (`Applications` wasn't a field I tried setting)

* the VPN warnings are still showing up for both custom rules

* the app doesn't seem to start up with either the old rules nor the new ones -- the start button has a spinner going around and incoming connections aren't being accepted

**Comment by xchacha20-poly1305** [comment]
Try [v0.6.1](https://github.com/xchacha20-poly1305/husi/releases/tag/v0.6.1) please.

**Comment by Terrance** [comment]
F-Droid (via IzzyOnDroid) updated me to 0.6.2, and this seems to fix most of these:

* I've set direct DNS to an external upstream (Quad9) which seems to work -- I'm assuming this is used to resolve the SSH server hostname
* the VPN warning has gone away now
* I can create or change IP/outbound-only rules now, though trying to edit and save without any changes still shows the _Empty Route_ error

For completeness, here are the rules as they stand:

<img src="https://github.com/xchacha20-poly1305/husi/assets/4025899/ad9f0b4f-1d97-47c4-b3d0-33c139de5711" width="300">
<img src="https://github.com/xchacha20-poly1305/husi/assets/4025899/e054c599-3f19-48e4-99b7-714cb8eeb62f" width="300">

<details>
<summary>Rules backup snippet</summary>

```json
{
  "rules": [
    "CQAAAAAAAAAEAAAAQQBwAG8AYwAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAxADcAMgAuADEANgAuADEALgAxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "CAAAAAAAAAAGAAAAQgB5AHAAYQBzAHMAAAAAAAMAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAMAAuADAALgAwAC4AMAAvADAACgA6ADoALwAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA__________8AAAAAAAAAAAAAAAAAAAAAAAAAAA"
  ]
}
```
</details>

**Comment by xchacha20-poly1305** [comment]
> I can create or change IP/outbound-only rules now, though trying to edit and save without any changes still shows the Empty Route error

If you didn't edit your route, this warning will be show.

DNS problem will be fixed next time.
