### ISSUE TITLE
快捷方式与NekoBox存在冲突

### ISSUE THREAD

**Issue by Typhonling** [xchacha20-poly1305/husi#47]
### 版本

```shell
0.5.4
```

### 描述

快捷方式存在2种错误。

### 重现方式

1.若以桌面图标快捷方式启动husi，则无法启动husi，会错误地启动NekoBox。
2.若在NekoBox已占用VPN的情况下使用intent启动husi（如使用Tasker），可正确切换到husi。但此时状态栏WiFi图标消失，快速磁贴显示无WIFI连接、有可用的网络，实际上WIFI仍连接且网络正常。

### 完整性要求

- [X] 我确定我的问题是 虎兕 本身的问题而不是我自身网络环境或服务器的问题。
- [X] 我保证提供了可以在本地重现该问题的配置文件与流程。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by xchacha20-poly1305** [comment]
快捷方式冲突问题已在 [v0.6.0-alpha.1](https://github.com/xchacha20-poly1305/husi/releases/tag/v0.6.0-alpha.1) 修复，但是切换功能好像坏了，以后修。

不保证其他使用方式（如 Tasker 可用性）。

**Comment by Typhonling** [comment]
更新一下第二个问题描述，在已有VPN连接的情况下（已测试Shadowsocks/Matsuri/NekoBox/husi），使用husi切换VPN（包括：主界面点击连接/主界面切换线路/快捷方式），状态栏Wifi图标消失，网络连接正常，部分软件因此误判未连接到互联网。
