### ISSUE TITLE
Fixes for android 14 QPR2 

### ISSUE THREAD

**Issue by dill-shower** [xchacha20-poly1305/husi#55]
### Version

```text
0.6.0-rc0
```

### Description

After upgrading to this version of OS husi started losing connection to proxy after the device goes into sleep mode. Internet is completely lost and restored after a couple of seconds after turning on the screen. Battery optimization is disabled, using the keep CPU option does not solve the problem.

P.s: this problem is also in nekobox

### Reproduction

Update OS
Use Husi
See lost connections

### Logs

```INFO[0954] [2800367243 7ms] inbound/mixed[mixed-in]: inbound connection to XXXXX
ERROR[0954] [2800367243 8ms] inbound/mixed[mixed-in]: process connection from XXXXXX: reject connection to XXXXXX while device paused
```
XXX proxy server 

### Integrity requirements

- [x] I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
- [x] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by xchacha20-poly1305** [comment]
If the connections recover finally, that is a feature, not a bug.
