### ISSUE TITLE
对 ChromeOS 安卓子系统上 network is unreachable 的补充与更新

### ISSUE THREAD

**Issue by gitiy1** [xchacha20-poly1305/husi#56]
### Version

```text
Husi：v0.6.0
Android：13，R122-15753.46.0 release-keys, security patch March 5th, 2024
```

### Description

更新：

&emsp;&emsp;在 #51 中的猜测有误，最近向 ChromeOS 的开发者反馈并附上了日志，以下是他们的回复：

>This may not be directly related to captive portal / Internet detection but to a related change in our Android integration layer about how ChromeOS advertises the NET_CAPABILITY_INTERNET bit to Android AOSP code for non-default network. I imagine you are using an Android VPN ? When an Android VPN is connected, Android sees all physical networks as non-default networks. On certain Chromebooks running Android T, we are removing the NET_CAPABILITY_INTERNET on such networks but this is to work around an Android T limitation when multiple physical networks are connected.

&emsp;&emsp;没有学习过安卓开发以及 Kotlin, Java，但我的 ChromeOS 在 122 版本时的安卓子系统确实是 Android 13，如果说在这种情况下连接 VPN 后其他物理网络（Wi-Fi，以太网，等等）将会被视为非默认网络，而且 NET_CAPABILITY_INTERNET 被移除，那么这似乎有了合理的解释。

&emsp;&emsp;尝试搜寻代码并阅读 husi/app/src/main/java/io/nekohasekai/sagernet/bg
/DefaultNetworkListener.kt，根据我的理解（很有可能有错误，希望加以指正）是当 API 版本介于 28 至 31 以及以上时，使用 request 对象以及 callback 对象进行注册，而在 24-28 仅使用 Callback 进行注册，而 request 对象调用了 NET_CAPABILITY_INTERNET，而且所有基于 Sagernet 进行开发的代理链均使用其以判断网络是否联通解决问题的办法似乎是在 ChromeOS 的 API 版本大于等于 33 的安卓子系统尝试使用 request 对象进行注册但由于 NET_CAPABILITY_INTERNET 被移除而失败，然后调用 Callback 对象并用到了 ConnectivityManager.NetworkCallback 方法，不知道其是否有涉及到 Captive Portal 机制，但个人猜测是有涉及到通过检测 Captive Portal 服务器的 204 是否返回来判断该 Wi-Fi 是否可访问互联网，当无法访问 Captive Portal 的 Google 服务器（http://clients3.google.com/generate_204） 时，将会返回 onLost ，因此所有调用 ConnectivityManager.NetworkCallback 以判断网络连接状态的 APP 均会认为网络无法访问，这似乎是当 Wi-FI 可以访问 Google 时虎兕可以正常使用的解释，并且这个检测似乎是周期性的，具体体现在当 Wi-Fi 上的可访问 Google 的代理被关闭后的一段时间内 Wi-Fi 右下角并不会出现叹号并且虎兕可以连接，但一段时间后 Wi-Fi 右下角又会出现叹号并且虎兕再度返回  network is unreachable。

&emsp;&emsp;判断是否为 ChromeOS 安卓子系统的方法可以通过检测是否有 org.chromium.arc.device_management 或者 org.chromium.arc 的 android 的 SystemFeature（参考了 [1](https://stackoverflow.com/questions/51489132/how-to-find-if-android-app-is-started-by-androidos-or-chromeoss-android-contain) [2](https://gist.github.com/TanaTanoi/d6a9655de74e53c0f0920d61f252fb13) [3](https://www.b4x.com/android/forum/threads/check-if-the-application-is-running-on-a-chromebook.145496/)），但由于对安卓开发以及对 Kotlin 以及 Java 的不了解导致不知如何实现相应的代码逻辑以及对该问题修复。

&emsp;&emsp;最后还是感谢开发者的付出！

### Reproduction

1. 更新 ChromeOS 版本至 M122，安卓子系统版本至 2024 年三月 5日，13。
2. 连接至无法访问 Google 的 Wi-Fi
3. 启动虎兕

### Integrity requirements

- [X] I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by xchacha20-poly1305** [comment]
1. sing-box for Android 客户端是否有相同的问题？
2. 您似乎有了修复思路，能否详细讲讲？

**Comment by gitiy1** [comment]
抱歉来晚了（

1. sing-box for Android 客户端亦会出现问题，debug 日志中输出 connection is refused.
2. 安卓开发不太了解，我的想法也就（可能有错误，需要指正）：
a. 是否有 org.chromium.arc.device_management 或者 org.chromium.arc 的 android 的 SystemFeature 来判断是否为 ChromeOS 的安卓子系统，并在此条件下采用另外的检测机制或者询问用户是否继续连接
b. 等待 ChromeOS 修复将连接 VPN 后将其他网络判定为非默认网络而且移除 NET_CAPABILITY_INTERNET 的 Bug。

**Comment by xchacha20-poly1305** [comment]
ChromeOS 并不是真正的安卓系统，我也没有在使用，~~更何况 sfa 也有同样的问题~~，暂时不修。

**Comment by gitiy1** [comment]
更新：ChromeOS M123 正式版更新基本修复了这个问题，感谢开发者的关注与付出！
