### ISSUE TITLE
vless节点全部显示“连接重置”，无法使用。

### ISSUE THREAD

**Issue by jjilan229** [xchacha20-poly1305/husi#60]
### 版本

```shell
所有版本
```

### 描述

vless节点全部显示“连接重置”，无法使用。

### 重现方式

vless节点全部显示“连接重置”，无法使用。

### 日志

```shell
noll
```

### 完整性要求

- [X] 我确定我的问题是 虎兕 本身的问题而不是我自身网络环境或服务器的问题。
- [X] 我保证提供了可以在本地重现该问题的配置文件与流程。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by jjilan229** [comment]
vless节点连接重置情况依旧存在，vmess节点多的节点也无法使用，显示连接重置

**Comment by jjilan229** [comment]
vless节点连接重置情况依旧存在，vmess节点多的节点也无法使用，显示连接重置

**Comment by xchacha20-poly1305** [comment]
可能有喜欢讨好最终用户的软件的维护者乐意为您 **服务**。
