### ISSUE TITLE
No connection after turning off and on mobile data

### ISSUE THREAD

**Issue by 10rino** [xchacha20-poly1305/husi#62]
### Version

```text
0.6.6
```

### Description

Hello, in the app, when I connect to the configuration and turn the mobile data off and on, although the connection is still established, no data is exchanged, and the configuration must be manually disconnected and connected again in order to use it.  There is a situation where the battery optimization is turned off and it was checked in several phones and the same problem was present

This is while the configuration in the program pings, but the programs that are proxying do not work until the configuration is restarted.

Is it possible to fix this bug and after turning the data off and on, the connection remains active and does not need manual reactivation?

### Reproduction

start config ( work correctly )
turn off data mobile 
turn on data mobile
No connection
To reconnect the configuration, it must be stopped and started manually

### Integrity requirements

- [X] I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by xchacha20-poly1305** [comment]
Try [v0.6.7](https://github.com/xchacha20-poly1305/husi/releases/tag/v0.6.7), please.

**Comment by 10rino** [comment]
Thanks, fixed
