### ISSUE TITLE
Can't connect to any proxy, the connect button is showing a endless circular animation

### ISSUE THREAD

**Issue by D3ZOXY** [xchacha20-poly1305/husi#66]
### Version

```text
0.6.6
```

### Description

Can't connect to any proxy, the connect button is showing a endless circular animation.

[18_03-08-25-06_714.log](https://github.com/xchacha20-poly1305/husi/files/14631487/18_03-08-25-06_714.log)

### Reproduction

1. Add any proxy.
2. Try to connect.

### Integrity requirements

- [X] I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by l3617** [comment]
是的，根本没法用，节点连接不上，一直转圈圈

**Comment by xchacha20-poly1305** [comment]
Bug of DNS

**Comment by xchacha20-poly1305** [comment]
Try [v0.6.7](https://github.com/xchacha20-poly1305/husi/releases/tag/v0.6.7), please.

**Comment by D3ZOXY** [comment]
Fixed.
