### ISSUE TITLE
Error when import other geoip or geosite

### ISSUE THREAD

**Issue by SighT26** [xchacha20-poly1305/husi#67]
### Version

```text
0.6.6
```

### Description

Import other *.db get the error _gzip: invalid header_

### Reproduction

I tried to import *.db from https://github.com/L11R/antizapret-sing-box-geo or generate my own with https://github.com/Dunamis4tw/generate-geoip-geosite and get error _gzip: invalid header_

### Integrity requirements

- [X] I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by xchacha20-poly1305** [comment]
Not support `.db` file
