### ISSUE TITLE
Critical request 

### ISSUE THREAD

**Issue by Graveyard9988** [xchacha20-poly1305/husi#70]
### 版本

```shell
..
```

### 描述

.

### 重现方式

Iranian users have to use "**Fragment**" but only this fork of nekobox supports that:
https://github.com/maskedeken/NekoBoxForAndroid

Please import this essential feature (it's available in "settings") because mentioned fork has crashes and issues. Here's a screenshot of the feature in mentioned fork:
![Screenshot_20240323_113516_NekoBox](https://github.com/xchacha20-poly1305/husi/assets/116078041/4c19f5a9-41f1-417d-88c5-bac77df75f98)

**We urgently need "fragment" in Husi app.**

Unfortunately, I'm not programmer and can't submit PR.

Regards

### 完整性要求

- [X] 我确定我的问题是 虎兕 本身的问题而不是我自身网络环境或服务器的问题。
- [X] 我保证提供了可以在本地重现该问题的配置文件与流程。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by xchacha20-poly1305** [comment]
No, you are spamming. Because official sing-box does not support fragment. If you need, please go to sing-box ask for help.

**Comment by xchacha20-poly1305** [comment]
Forgive
