### ISSUE TITLE
vless节点连接重置情况依旧存在，vmess节点多的节点也无法使用，显示连接重置

### ISSUE THREAD

**Issue by jjilan229** [xchacha20-poly1305/husi#71]
### Version

```text
vless节点连接重置情况依旧存在，vmess节点多的节点也无法使用，显示连接重置
```

### Description

vless节点连接重置情况依旧存在，vmess节点多的节点也无法使用，显示连接重置

### Reproduction

vless节点连接重置情况依旧存在，vmess节点多的节点也无法使用，显示连接重置

### Logs

```shell
vless节点连接重置情况依旧存在，vmess节点多的节点也无法使用，显示连接重置
```

### Integrity requirements

- [X] I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by xchacha20-poly1305** [comment]
请寻求以服务最终用户为乐的开发者的慷慨服务。

**Comment by xchacha20-poly1305** [comment]
> 虎兕 不是讨好无法作出任何意义上的贡献的最终用户并获取非道德影响力的项目，也不是为 “机场” 黑产服务的客户端，更不是广告引流工具。如果您在此处欺骗以故意浪费开发者的时间，您将被永久封锁。
