### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dill-shower** [xchacha20-poly1305/husi#72]
### Version

```text
1.3.1
```

### Description

Use vless and get this error every time after ≈5min working 

### Reproduction

. 

### Logs

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xda58a837f954]

goroutine 17 [running, locked to thread]:
libcore.(*BoxInstance).Sleep(0x40004352c0)
	libcore@v0.0.0-00010101000000-000000000000/box.go:151 +0x24
main.proxylibcore_BoxInstance_Sleep(0xffffff01?)
	gobind/gobind/go_libcoremain.go:128 +0x38
```

### Integrity requirements

- [X] I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by xchacha20-poly1305** [comment]
We don't have version `1.3.1`, and you just put a little port of logs.

**Comment by xchacha20-poly1305** [comment]
Our `box.go:151` not about pause manager.

https://github.com/xchacha20-poly1305/husi/blob/99bd977f594b69d54861305ee8809b191dcde934/libcore/box.go#L151

But some advertisement softwere is:

https://github.com/MatsuriDayo/NekoBoxForAndroid/blob/595ed091f933a5359756d08c0ab4ff85f874b8fa/libcore/box.go#L151
