### ISSUE TITLE
不支持singbox格式？

### ISSUE THREAD

**Issue by qixi202303** [xchacha20-poly1305/husi#75]
### 版本

```shell
0.6.6
```

### 描述

加了一个订阅，在app节点里显示sing-box config。
但一点击启用这个就闪退。但这个订阅在neko1.2.9正常显示所有具体节点

### 重现方式

点击启用分组的sing-box config的就闪退

### 完整性要求

- [X] 我确定我的问题是 虎兕 本身的问题而不是我自身网络环境或服务器的问题。
- [X] 我保证提供了可以在本地重现该问题的配置文件与流程。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by xchacha20-poly1305** [comment]
日志，还有你分组编辑界面的截图（记得订阅地址打码）。
