### ISSUE TITLE
Wireguard chains don't work

### ISSUE THREAD

**Issue by OBrein** [xchacha20-poly1305/husi#77]
### Version

```text
0.6.7, 0.6.8
```

### Description

Chains with wireguard servers, as well as groups of wireguard servers with the "front proxy" setting do not work. The only error in the log is WARN[0112] [StatsBar$TestConnection$1] java.lang.IllegalStateException: Timeout
Android 14

### Reproduction

Just add chain Shadowsocks - Wireguard 

### Logs

```shell
WARN[0000] inbound/tun[tun-in]: bind forwarder to interface: no such device
ERROR[0000] [3812474424 12ms] inbound/tun[tun-in]: dial tcp 127.0.0.1:853: connect: connection refused
WARN[0112] [StatsBar$testConnection$1] java.lang.IllegalStateException: Тайм-аут
```

### Integrity requirements

- [X] I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by OBrein** [comment]
UPD: 
I tested different settings on the debug version (commit d4126d7). If there is a sing-box core on the server side, then the chains work fine. For another kernel, I need to disable multiplex and the udp-over-tcp option in shadowsocks.
I think you can close the issue. These are not husi error, but the features of the sing-box core itself. The chains work with the correct husi settings.

**Comment by xchacha20-poly1305** [comment]
Yes, sing-mux and sing-uot is not being supported widely. Thank you for your patience to find the answer.
