### ISSUE TITLE
When Use selector is on,don't connect any config

### ISSUE THREAD

**Issue by Amir2367** [xchacha20-poly1305/husi#80]
### Version

```text
0.6.8
```

### Description

When USE SELECTOR is on, it shows the following error and the connection is unsuccessful.

https://github.com/xchacha20-poly1305/husi/assets/83357422/a55db506-0829-41ea-b349-6d95a7998dd3

### Reproduction

When USE SELECTOR is on, it shows the following error and the connection is unsuccessful.

### Integrity requirements

- [X] I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
- [x] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by xchacha20-poly1305** [comment]
Restart the application
