### ISSUE TITLE
not working connection button,and crash app when chain two wireguards

### ISSUE THREAD

**Issue by Amir2367** [xchacha20-poly1305/husi#82]
### Version

```text
0.6.8
```

### Description

When we want to chain two wireguards together, the connection button no longer works and we have to close the app completely and enter the app again.

https://github.com/xchacha20-poly1305/husi/assets/83357422/27de9151-6541-4c00-b65a-b9584f01c5f8

### Reproduction

When we want to chain two wireguards together, the connection button no longer works and we have to close the app completely and enter the app again.

### Integrity requirements

- [X] I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
- [x] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
- [ ] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by xchacha20-poly1305** [comment]
Try [v0.7.0-beta.0](https://github.com/xchacha20-poly1305/husi/releases/tag/v0.7.0-beta.0)

**Comment by Amir2367** [comment]
> Try [v0.7.0-beta.0](https://github.com/xchacha20-poly1305/husi/releases/tag/v0.7.0-beta.0)

I tested the new version but the problem was not solved


https://github.com/xchacha20-poly1305/husi/assets/83357422/319659f3-3002-4e62-ac43-f433dcf4ce45

**Comment by Amir2367** [comment]
> Try [v0.7.0-beta.0](https://github.com/xchacha20-poly1305/husi/releases/tag/v0.7.0-beta.0)


Thanks to your good team
I hope the Chain problem in Wireguard configurations to be solved.

Because it is important for traders and some sites that do not open in embargoed areas.

**Comment by Amir2367** [comment]
> Try [v0.7.0-beta.0](https://github.com/xchacha20-poly1305/husi/releases/tag/v0.7.0-beta.0)




I suggest to use the stable versions of Singbox core (the latest stable version: 1.8.12) in the program, probably the problem will be solved.

Thanks to your good team
I hope the Chain problem in Wireguard configurations to be solved.

Because it is important for traders and some sites that do not open in embargoed areas.

**Comment by Amir2367** [comment]
@Mahdi-zarei

**Comment by Amir2367** [comment]
> ### Version
> ```
> 0.6.8
> ```
> 
> ### Description
> When we want to chain two wireguards together, the connection button no longer works and we have to close the app completely and enter the app again.
> 
>  Screenrecorder-2024-04-11-16-35-42-602.mp4 
> ### Reproduction
> When we want to chain two wireguards together, the connection button no longer works and we have to close the app completely and enter the app again.
> 
> ### Logs
> _No response_
> 
> ### Integrity requirements
> * [x]  I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
> * [x]  I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
> * [ ]  I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

@Mahdi-zarei

**Comment by Mahdi-zarei** [comment]
@xchacha20-poly1305 I tried to find out what the problem is, and it appears that sing-box does not close properly when 2 wireguard instances are chained ( it actually takes a long time to exit) , and this prevents the next sing-box instance from starting as the previous one is holding the clash-api listen port ( and maybe some other resources related to the wireguard stack? ). This practically cannot be solved unless we somehow kill the process of core when it does not close in time.

**Comment by Amir2367** [comment]
> @xchacha20-poly1305 I tried to find out what the problem is, and it appears that sing-box does not close properly when 2 wireguard instances are chained ( it actually takes a long time to exit) , and this prevents the next sing-box instance from starting as the previous one is holding the clash-api listen port ( and maybe some other resources related to the wireguard stack? ). This practically cannot be solved unless we somehow kill the process of core when it does not close in time.

Is there an advantage to using the beta and alpha updates of Singbox core in the program which usually has many bugs?
What is the reason for not using stable singbox versions?
Can't this item fix many of the program's problems and bugs?

**Comment by Mahdi-zarei** [comment]
> > @xchacha20-poly1305 I tried to find out what the problem is, and it appears that sing-box does not close properly when 2 wireguard instances are chained ( it actually takes a long time to exit) , and this prevents the next sing-box instance from starting as the previous one is holding the clash-api listen port ( and maybe some other resources related to the wireguard stack? ). This practically cannot be solved unless we somehow kill the process of core when it does not close in time.
> 
> Is there an advantage to using the beta and alpha updates of Singbox core in the program which usually has many bugs? What is the reason for not using stable singbox versions? Can't this item fix many of the program's problems and bugs?

This has nothing to do with the alpha and beta versions of sing-box. This is practically an issue and not a bug concerning sing-box, as it takes a long time to terminate. The stable release of the sing-box does have this problem as well.

**Comment by Amir2367** [comment]
> This has nothing to do with the alpha and beta versions of sing-box. This is practically an issue and not a bug concerning sing-box, as it takes a long time to terminate. The stable release of the sing-box does have this problem as well.



No, this was a general question and I asked it separately from the previous problem.
