### ISSUE TITLE
Warp让程序卡死的bug

### ISSUE THREAD

**Issue by i5g5vip** [xchacha20-poly1305/husi#84]
### 版本

```shell
warp三个必死
```

### 描述

1.连通任意类型的节点，切换到warp必死。
2.使用warp节点时，网络中断必死，比如从WiFi切换到流量。
3.两个warp节点做链式代理，依次操作连通成功，断开连接，再次连接必死。

### 重现方式

1.连通任意类型的节点，切换到warp必死。
2.使用warp节点时，网络中断必死，比如从WiFi切换到流量。
3.两个warp节点做链式代理，依次操作连通成功，断开连接，再次连接必死。

可以随时无限复现。

### 完整性要求

- [X] 我确定我的问题是 虎兕 本身的问题而不是我自身网络环境或服务器的问题。
- [X] 我保证提供了可以在本地重现该问题的配置文件与流程。
- [ ] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by xchacha20-poly1305** [comment]
Duplicate with #81 #82
