### ISSUE TITLE
When share a config, the app is freezes and automatically exits

### ISSUE THREAD

**Issue by Amir2367** [xchacha20-poly1305/husi#85]
### Version

```text
0.7.0 alpha 0 and alpha 1
```

### Description

In the new version, when we want to share a configuration
The program freezes and automatically exits (this was not a problem in version 0.6.8)

https://github.com/xchacha20-poly1305/husi/assets/83357422/2b8b4f8e-e1b2-4192-ab9e-d09442eef627

### Reproduction

In the new version, when we want to share a configuration
The program freezes and automatically exits (this was not a problem in version 0.6.8)

### Integrity requirements

- [X] I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by xchacha20-poly1305** [comment]
[v0.7.0-alpha.2](https://github.com/xchacha20-poly1305/husi/releases/tag/v0.7.0-alpha.2)
e7bd9374eb1ae6870bc85df60abf007091b6663c
