### ISSUE TITLE
hystrria2链接的bug

### ISSUE THREAD

**Issue by i5g5vip** [xchacha20-poly1305/husi#87]
### Version

```text
在密码与@之间多了一个 ":"。
导致导出的链接在另外一些app上不兼容。
```

### Description

在密码与@之间多了一个 ":"冒号。
导致导出的链接在另外一些app上不兼容。

### Reproduction

冒号

### Integrity requirements

- [X] I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
- [ ] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by xchacha20-poly1305** [comment]
请提供链接示例
