### ISSUE TITLE
切换网络或网络断开重连

### ISSUE THREAD

**Issue by ApolloRioo** [xchacha20-poly1305/husi#88]
### 版本

```shell
v0.7.0-alpha.2
```

### 描述

会导致网络成为流量模式，需要重载节点才会正常

### 重现方式

切换网络或网络断开重连

### 完整性要求

- [X] 我确定我的问题是 虎兕 本身的问题而不是我自身网络环境或服务器的问题。
- [X] 我保证提供了可以在本地重现该问题的配置文件与流程。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by yuyahui811** [comment]
有这回事，连接时间长了，特别时熄屏久了。wifi变成不可用。

**Comment by Amir2367** [comment]
> This happens when the connection takes a long time, especially when the screen is turned off for a long time. wifi becomes unavailable.

Yes, I have the same problem

**Comment by xchacha20-poly1305** [comment]
> 会导致网络成为流量模式

描述不具体，并且没日志
