### ISSUE TITLE
Bug of wierguard client

### ISSUE THREAD

**Issue by Mhrpoor77** [xchacha20-poly1305/husi#92]
### Description

Dont work wierguard client in husi app

### Reproduction

Dont work wierguard client in husi app

### Integrity requirements

- [X] I confirm that my problem is the bug of husi, but not the problem of my own network environment or my server.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported.
- [ ] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by Mhrpoor77** [comment]
Please fix it

**Comment by Mhrpoor77** [comment]
Dont work wierguard client in husi app

**Comment by xchacha20-poly1305** [comment]
Dulplicate: #81 ＃82
