### ISSUE TITLE
vless链接不兼容

### ISSUE THREAD

**Issue by i5g5vip** [xchacha20-poly1305/husi#93]
### 版本

```shell
全部版本
```

### 描述

vless标准分享链接与karing不兼容，
vless非reality标准分享链接与hiddify不兼容。

### 重现方式

与nekobox和catbox的vless链接差异很大，但彼此兼容，并不清楚谁不标准。

### 完整性要求

- [X] 我确定我的问题是 虎兕 本身的问题而不是我自身网络环境或服务器的问题。
- [X] 我保证提供了可以在本地重现该问题的配置文件与流程。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by xchacha20-poly1305** [comment]
现有 VLESS 链接标准完全遵循 [Xray](https://github.com/XTLS/Xray-core/discussions/716) 标准，如有不兼容之处请给出例子。

**Comment by xchacha20-poly1305** [comment]
![k](https://github.com/xchacha20-poly1305/husi/assets/139959885/a03117b8-b7f4-4a31-94f1-39e22df9d444)

另外，karing 宣传使用 sing-box，但却没有遵守 sing-box 的开源许可证，SagerNet 开发者正在积极寻找相关制裁措施。我拒绝为非自由软件提供支持。
