### ISSUE TITLE
一些老bug Warp

### ISSUE THREAD

**Issue by yuyahui811** [xchacha20-poly1305/husi#95]
### 版本

```shell
0.5.0-alpha1
之后版本
```

### 描述

这个bug之前有人提过，
并不是说没有改域名和端口联不通，
是改了域名和端口可以连通，是切换的bug
是从任意一个联通的节点切换的这个warp节点，
就会卡住，连接开关就无响应了，只能结束任务。
0.5.0-alpha1及之前的版本无问题

### 重现方式

最简单的呈现方式，
用两个warp节点。
联通一个，然后切换到另一个就会复现

### 日志

```shell
看了日志没有异常表现
```

### 完整性要求

- [X] 我确定我的问题是 虎兕 本身的问题而不是我自身网络环境或服务器的问题。
- [X] 我保证提供了可以在本地重现该问题的配置文件与流程。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by yuyahui811** [comment]
另外，vless链接，也有人提过，
flow为空时，husi的链接多了一个
flow=auto
导致一些其他代理软件识别不了

**Comment by xchacha20-poly1305** [comment]
#81 #82
